[package]
authors       = ["Ethan Frey <ethanfrey@users.noreply.github.com>", "Orkun Külçe <orkun@deuslabs.fi>"]
description   = "Definition and types for the CosmWasm-721 NFT interface"
documentation = { workspace = true }
edition       = { workspace = true }
homepage      = { workspace = true }
license       = { workspace = true }
name          = "cw721"
repository    = { workspace = true }
version       = { workspace = true }

[lib]
doctest = false # disable doc tests

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std    = { workspace = true }
cw-ownable      = { workspace = true }
cw-storage-plus = { workspace = true }
cw-utils        = { workspace = true }
cw2             = { workspace = true }
schemars        = { workspace = true }
serde           = { workspace = true }
thiserror       = { workspace = true }
url             = { workspace = true }

[dev-dependencies]
anyhow        = { workspace = true }
bech32        = { workspace = true }
cw-multi-test = { workspace = true }
sha2          = { workspace = true }
